/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResearchIndexRouteImport } from './routes/research/index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as QuizzesIdRouteImport } from './routes/quizzes/$id'
import { Route as CoursesIdRouteImport } from './routes/courses/$id'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as QuizzesIdResultsRouteImport } from './routes/quizzes/$id.results'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminAdminUsersIndexRouteImport } from './routes/_admin/admin/users/index'
import { Route as AdminAdminResourcesIndexRouteImport } from './routes/_admin/admin/resources/index'
import { Route as AdminAdminQuizzesIndexRouteImport } from './routes/_admin/admin/quizzes/index'
import { Route as AdminAdminCoursesIndexRouteImport } from './routes/_admin/admin/courses/index'
import { Route as AdminAdminContactsIndexRouteImport } from './routes/_admin/admin/contacts/index'
import { Route as AdminAdminArticlesIndexRouteImport } from './routes/_admin/admin/articles/index'
import { Route as CoursesIdModulesModuleIdRouteImport } from './routes/courses/$id.modules.$moduleId'
import { Route as AdminAdminResourcesCreateRouteImport } from './routes/_admin/admin/resources/create'
import { Route as AdminAdminResourcesIdRouteImport } from './routes/_admin/admin/resources/$id'
import { Route as AdminAdminQuizzesCreateRouteImport } from './routes/_admin/admin/quizzes/create'
import { Route as AdminAdminQuizzesIdRouteImport } from './routes/_admin/admin/quizzes/$id'
import { Route as AdminAdminCoursesCreateRouteImport } from './routes/_admin/admin/courses/create'
import { Route as AdminAdminCoursesIdRouteImport } from './routes/_admin/admin/courses/$id'
import { Route as AdminAdminArticlesCreateRouteImport } from './routes/_admin/admin/articles/create'
import { Route as AdminAdminArticlesIdRouteImport } from './routes/_admin/admin/articles/$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_admin/route.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIdRoute = QuizzesIdRouteImport.update({
  id: '/quizzes/$id',
  path: '/quizzes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_admin/admin/index.lazy').then((d) => d.Route),
)
const QuizzesIdResultsRoute = QuizzesIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => QuizzesIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminUsersIndexRoute = AdminAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_admin/admin/users/index.lazy').then((d) => d.Route),
)
const AdminAdminResourcesIndexRoute =
  AdminAdminResourcesIndexRouteImport.update({
    id: '/admin/resources/',
    path: '/admin/resources/',
    getParentRoute: () => AdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_admin/admin/resources/index.lazy').then((d) => d.Route),
  )
const AdminAdminQuizzesIndexRoute = AdminAdminQuizzesIndexRouteImport.update({
  id: '/admin/quizzes/',
  path: '/admin/quizzes/',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_admin/admin/quizzes/index.lazy').then((d) => d.Route),
)
const AdminAdminCoursesIndexRoute = AdminAdminCoursesIndexRouteImport.update({
  id: '/admin/courses/',
  path: '/admin/courses/',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_admin/admin/courses/index.lazy').then((d) => d.Route),
)
const AdminAdminContactsIndexRoute = AdminAdminContactsIndexRouteImport.update({
  id: '/admin/contacts/',
  path: '/admin/contacts/',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_admin/admin/contacts/index.lazy').then((d) => d.Route),
)
const AdminAdminArticlesIndexRoute = AdminAdminArticlesIndexRouteImport.update({
  id: '/admin/articles/',
  path: '/admin/articles/',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_admin/admin/articles/index.lazy').then((d) => d.Route),
)
const CoursesIdModulesModuleIdRoute =
  CoursesIdModulesModuleIdRouteImport.update({
    id: '/modules/$moduleId',
    path: '/modules/$moduleId',
    getParentRoute: () => CoursesIdRoute,
  } as any)
const AdminAdminResourcesCreateRoute =
  AdminAdminResourcesCreateRouteImport.update({
    id: '/admin/resources/create',
    path: '/admin/resources/create',
    getParentRoute: () => AdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_admin/admin/resources/create.lazy').then((d) => d.Route),
  )
const AdminAdminResourcesIdRoute = AdminAdminResourcesIdRouteImport.update({
  id: '/admin/resources/$id',
  path: '/admin/resources/$id',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_admin/admin/resources/$id.lazy').then((d) => d.Route),
)
const AdminAdminQuizzesCreateRoute = AdminAdminQuizzesCreateRouteImport.update({
  id: '/admin/quizzes/create',
  path: '/admin/quizzes/create',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_admin/admin/quizzes/create.lazy').then((d) => d.Route),
)
const AdminAdminQuizzesIdRoute = AdminAdminQuizzesIdRouteImport.update({
  id: '/admin/quizzes/$id',
  path: '/admin/quizzes/$id',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_admin/admin/quizzes/$id.lazy').then((d) => d.Route),
)
const AdminAdminCoursesCreateRoute = AdminAdminCoursesCreateRouteImport.update({
  id: '/admin/courses/create',
  path: '/admin/courses/create',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_admin/admin/courses/create.lazy').then((d) => d.Route),
)
const AdminAdminCoursesIdRoute = AdminAdminCoursesIdRouteImport.update({
  id: '/admin/courses/$id',
  path: '/admin/courses/$id',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_admin/admin/courses/$id.lazy').then((d) => d.Route),
)
const AdminAdminArticlesCreateRoute =
  AdminAdminArticlesCreateRouteImport.update({
    id: '/admin/articles/create',
    path: '/admin/articles/create',
    getParentRoute: () => AdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_admin/admin/articles/create.lazy').then((d) => d.Route),
  )
const AdminAdminArticlesIdRoute = AdminAdminArticlesIdRouteImport.update({
  id: '/admin/articles/$id',
  path: '/admin/articles/$id',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_admin/admin/articles/$id.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/courses/$id': typeof CoursesIdRouteWithChildren
  '/quizzes/$id': typeof QuizzesIdRouteWithChildren
  '/articles/': typeof ArticlesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/quizzes/$id/results': typeof QuizzesIdResultsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/admin/articles/$id': typeof AdminAdminArticlesIdRoute
  '/admin/articles/create': typeof AdminAdminArticlesCreateRoute
  '/admin/courses/$id': typeof AdminAdminCoursesIdRoute
  '/admin/courses/create': typeof AdminAdminCoursesCreateRoute
  '/admin/quizzes/$id': typeof AdminAdminQuizzesIdRoute
  '/admin/quizzes/create': typeof AdminAdminQuizzesCreateRoute
  '/admin/resources/$id': typeof AdminAdminResourcesIdRoute
  '/admin/resources/create': typeof AdminAdminResourcesCreateRoute
  '/courses/$id/modules/$moduleId': typeof CoursesIdModulesModuleIdRoute
  '/admin/articles/': typeof AdminAdminArticlesIndexRoute
  '/admin/contacts/': typeof AdminAdminContactsIndexRoute
  '/admin/courses/': typeof AdminAdminCoursesIndexRoute
  '/admin/quizzes/': typeof AdminAdminQuizzesIndexRoute
  '/admin/resources/': typeof AdminAdminResourcesIndexRoute
  '/admin/users/': typeof AdminAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/courses/$id': typeof CoursesIdRouteWithChildren
  '/quizzes/$id': typeof QuizzesIdRouteWithChildren
  '/articles': typeof ArticlesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/research': typeof ResearchIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/quizzes/$id/results': typeof QuizzesIdResultsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/admin/articles/$id': typeof AdminAdminArticlesIdRoute
  '/admin/articles/create': typeof AdminAdminArticlesCreateRoute
  '/admin/courses/$id': typeof AdminAdminCoursesIdRoute
  '/admin/courses/create': typeof AdminAdminCoursesCreateRoute
  '/admin/quizzes/$id': typeof AdminAdminQuizzesIdRoute
  '/admin/quizzes/create': typeof AdminAdminQuizzesCreateRoute
  '/admin/resources/$id': typeof AdminAdminResourcesIdRoute
  '/admin/resources/create': typeof AdminAdminResourcesCreateRoute
  '/courses/$id/modules/$moduleId': typeof CoursesIdModulesModuleIdRoute
  '/admin/articles': typeof AdminAdminArticlesIndexRoute
  '/admin/contacts': typeof AdminAdminContactsIndexRoute
  '/admin/courses': typeof AdminAdminCoursesIndexRoute
  '/admin/quizzes': typeof AdminAdminQuizzesIndexRoute
  '/admin/resources': typeof AdminAdminResourcesIndexRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/courses/$id': typeof CoursesIdRouteWithChildren
  '/quizzes/$id': typeof QuizzesIdRouteWithChildren
  '/articles/': typeof ArticlesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/quizzes/$id/results': typeof QuizzesIdResultsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_admin/admin/articles/$id': typeof AdminAdminArticlesIdRoute
  '/_admin/admin/articles/create': typeof AdminAdminArticlesCreateRoute
  '/_admin/admin/courses/$id': typeof AdminAdminCoursesIdRoute
  '/_admin/admin/courses/create': typeof AdminAdminCoursesCreateRoute
  '/_admin/admin/quizzes/$id': typeof AdminAdminQuizzesIdRoute
  '/_admin/admin/quizzes/create': typeof AdminAdminQuizzesCreateRoute
  '/_admin/admin/resources/$id': typeof AdminAdminResourcesIdRoute
  '/_admin/admin/resources/create': typeof AdminAdminResourcesCreateRoute
  '/courses/$id/modules/$moduleId': typeof CoursesIdModulesModuleIdRoute
  '/_admin/admin/articles/': typeof AdminAdminArticlesIndexRoute
  '/_admin/admin/contacts/': typeof AdminAdminContactsIndexRoute
  '/_admin/admin/courses/': typeof AdminAdminCoursesIndexRoute
  '/_admin/admin/quizzes/': typeof AdminAdminQuizzesIndexRoute
  '/_admin/admin/resources/': typeof AdminAdminResourcesIndexRoute
  '/_admin/admin/users/': typeof AdminAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/articles/$slug'
    | '/courses/$id'
    | '/quizzes/$id'
    | '/articles/'
    | '/courses/'
    | '/quizzes/'
    | '/research/'
    | '/resources/'
    | '/api/auth/$'
    | '/quizzes/$id/results'
    | '/admin/'
    | '/dashboard/'
    | '/admin/articles/$id'
    | '/admin/articles/create'
    | '/admin/courses/$id'
    | '/admin/courses/create'
    | '/admin/quizzes/$id'
    | '/admin/quizzes/create'
    | '/admin/resources/$id'
    | '/admin/resources/create'
    | '/courses/$id/modules/$moduleId'
    | '/admin/articles/'
    | '/admin/contacts/'
    | '/admin/courses/'
    | '/admin/quizzes/'
    | '/admin/resources/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/articles/$slug'
    | '/courses/$id'
    | '/quizzes/$id'
    | '/articles'
    | '/courses'
    | '/quizzes'
    | '/research'
    | '/resources'
    | '/api/auth/$'
    | '/quizzes/$id/results'
    | '/admin'
    | '/dashboard'
    | '/admin/articles/$id'
    | '/admin/articles/create'
    | '/admin/courses/$id'
    | '/admin/courses/create'
    | '/admin/quizzes/$id'
    | '/admin/quizzes/create'
    | '/admin/resources/$id'
    | '/admin/resources/create'
    | '/courses/$id/modules/$moduleId'
    | '/admin/articles'
    | '/admin/contacts'
    | '/admin/courses'
    | '/admin/quizzes'
    | '/admin/resources'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authed'
    | '/about'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/articles/$slug'
    | '/courses/$id'
    | '/quizzes/$id'
    | '/articles/'
    | '/courses/'
    | '/quizzes/'
    | '/research/'
    | '/resources/'
    | '/api/auth/$'
    | '/quizzes/$id/results'
    | '/_admin/admin/'
    | '/_authed/dashboard/'
    | '/_admin/admin/articles/$id'
    | '/_admin/admin/articles/create'
    | '/_admin/admin/courses/$id'
    | '/_admin/admin/courses/create'
    | '/_admin/admin/quizzes/$id'
    | '/_admin/admin/quizzes/create'
    | '/_admin/admin/resources/$id'
    | '/_admin/admin/resources/create'
    | '/courses/$id/modules/$moduleId'
    | '/_admin/admin/articles/'
    | '/_admin/admin/contacts/'
    | '/_admin/admin/courses/'
    | '/_admin/admin/quizzes/'
    | '/_admin/admin/resources/'
    | '/_admin/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  CoursesIdRoute: typeof CoursesIdRouteWithChildren
  QuizzesIdRoute: typeof QuizzesIdRouteWithChildren
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$id': {
      id: '/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof QuizzesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/quizzes/$id/results': {
      id: '/quizzes/$id/results'
      path: '/results'
      fullPath: '/quizzes/$id/results'
      preLoaderRoute: typeof QuizzesIdResultsRouteImport
      parentRoute: typeof QuizzesIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/users/': {
      id: '/_admin/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminAdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/resources/': {
      id: '/_admin/admin/resources/'
      path: '/admin/resources'
      fullPath: '/admin/resources/'
      preLoaderRoute: typeof AdminAdminResourcesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/quizzes/': {
      id: '/_admin/admin/quizzes/'
      path: '/admin/quizzes'
      fullPath: '/admin/quizzes/'
      preLoaderRoute: typeof AdminAdminQuizzesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/courses/': {
      id: '/_admin/admin/courses/'
      path: '/admin/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminAdminCoursesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/contacts/': {
      id: '/_admin/admin/contacts/'
      path: '/admin/contacts'
      fullPath: '/admin/contacts/'
      preLoaderRoute: typeof AdminAdminContactsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/articles/': {
      id: '/_admin/admin/articles/'
      path: '/admin/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminAdminArticlesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/courses/$id/modules/$moduleId': {
      id: '/courses/$id/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/courses/$id/modules/$moduleId'
      preLoaderRoute: typeof CoursesIdModulesModuleIdRouteImport
      parentRoute: typeof CoursesIdRoute
    }
    '/_admin/admin/resources/create': {
      id: '/_admin/admin/resources/create'
      path: '/admin/resources/create'
      fullPath: '/admin/resources/create'
      preLoaderRoute: typeof AdminAdminResourcesCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/resources/$id': {
      id: '/_admin/admin/resources/$id'
      path: '/admin/resources/$id'
      fullPath: '/admin/resources/$id'
      preLoaderRoute: typeof AdminAdminResourcesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/quizzes/create': {
      id: '/_admin/admin/quizzes/create'
      path: '/admin/quizzes/create'
      fullPath: '/admin/quizzes/create'
      preLoaderRoute: typeof AdminAdminQuizzesCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/quizzes/$id': {
      id: '/_admin/admin/quizzes/$id'
      path: '/admin/quizzes/$id'
      fullPath: '/admin/quizzes/$id'
      preLoaderRoute: typeof AdminAdminQuizzesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/courses/create': {
      id: '/_admin/admin/courses/create'
      path: '/admin/courses/create'
      fullPath: '/admin/courses/create'
      preLoaderRoute: typeof AdminAdminCoursesCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/courses/$id': {
      id: '/_admin/admin/courses/$id'
      path: '/admin/courses/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AdminAdminCoursesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/articles/create': {
      id: '/_admin/admin/articles/create'
      path: '/admin/articles/create'
      fullPath: '/admin/articles/create'
      preLoaderRoute: typeof AdminAdminArticlesCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/articles/$id': {
      id: '/_admin/admin/articles/$id'
      path: '/admin/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminAdminArticlesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminArticlesIdRoute: typeof AdminAdminArticlesIdRoute
  AdminAdminArticlesCreateRoute: typeof AdminAdminArticlesCreateRoute
  AdminAdminCoursesIdRoute: typeof AdminAdminCoursesIdRoute
  AdminAdminCoursesCreateRoute: typeof AdminAdminCoursesCreateRoute
  AdminAdminQuizzesIdRoute: typeof AdminAdminQuizzesIdRoute
  AdminAdminQuizzesCreateRoute: typeof AdminAdminQuizzesCreateRoute
  AdminAdminResourcesIdRoute: typeof AdminAdminResourcesIdRoute
  AdminAdminResourcesCreateRoute: typeof AdminAdminResourcesCreateRoute
  AdminAdminArticlesIndexRoute: typeof AdminAdminArticlesIndexRoute
  AdminAdminContactsIndexRoute: typeof AdminAdminContactsIndexRoute
  AdminAdminCoursesIndexRoute: typeof AdminAdminCoursesIndexRoute
  AdminAdminQuizzesIndexRoute: typeof AdminAdminQuizzesIndexRoute
  AdminAdminResourcesIndexRoute: typeof AdminAdminResourcesIndexRoute
  AdminAdminUsersIndexRoute: typeof AdminAdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminArticlesIdRoute: AdminAdminArticlesIdRoute,
  AdminAdminArticlesCreateRoute: AdminAdminArticlesCreateRoute,
  AdminAdminCoursesIdRoute: AdminAdminCoursesIdRoute,
  AdminAdminCoursesCreateRoute: AdminAdminCoursesCreateRoute,
  AdminAdminQuizzesIdRoute: AdminAdminQuizzesIdRoute,
  AdminAdminQuizzesCreateRoute: AdminAdminQuizzesCreateRoute,
  AdminAdminResourcesIdRoute: AdminAdminResourcesIdRoute,
  AdminAdminResourcesCreateRoute: AdminAdminResourcesCreateRoute,
  AdminAdminArticlesIndexRoute: AdminAdminArticlesIndexRoute,
  AdminAdminContactsIndexRoute: AdminAdminContactsIndexRoute,
  AdminAdminCoursesIndexRoute: AdminAdminCoursesIndexRoute,
  AdminAdminQuizzesIndexRoute: AdminAdminQuizzesIndexRoute,
  AdminAdminResourcesIndexRoute: AdminAdminResourcesIndexRoute,
  AdminAdminUsersIndexRoute: AdminAdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface CoursesIdRouteChildren {
  CoursesIdModulesModuleIdRoute: typeof CoursesIdModulesModuleIdRoute
}

const CoursesIdRouteChildren: CoursesIdRouteChildren = {
  CoursesIdModulesModuleIdRoute: CoursesIdModulesModuleIdRoute,
}

const CoursesIdRouteWithChildren = CoursesIdRoute._addFileChildren(
  CoursesIdRouteChildren,
)

interface QuizzesIdRouteChildren {
  QuizzesIdResultsRoute: typeof QuizzesIdResultsRoute
}

const QuizzesIdRouteChildren: QuizzesIdRouteChildren = {
  QuizzesIdResultsRoute: QuizzesIdResultsRoute,
}

const QuizzesIdRouteWithChildren = QuizzesIdRoute._addFileChildren(
  QuizzesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  CoursesIdRoute: CoursesIdRouteWithChildren,
  QuizzesIdRoute: QuizzesIdRouteWithChildren,
  ArticlesIndexRoute: ArticlesIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
